create table if not exists public.game_high_scores (
  id bigint generated by default as identity primary key,
  game_name text not null,
  nickname text not null,
  score integer not null,
  last_stage integer,
  created_at timestamp with time zone not null default timezone('utc', now()),
  updated_at timestamp with time zone not null default timezone('utc', now()),
  constraint game_high_scores_game_name_nickname_key unique (game_name, nickname),
  constraint game_high_scores_game_name_not_blank check (char_length(btrim(game_name)) between 1 and 80),
  constraint game_high_scores_nickname_not_blank check (char_length(btrim(nickname)) between 1 and 24),
  constraint game_high_scores_score_non_negative check (score >= 0),
  constraint game_high_scores_last_stage_non_negative check (last_stage is null or last_stage >= 0)
);

create index if not exists game_high_scores_game_name_score_idx
on public.game_high_scores (game_name, score desc, updated_at asc);

alter table public.game_high_scores enable row level security;

create policy "Anyone can read high scores"
on public.game_high_scores
for select
to anon, authenticated
using (true);

create or replace function public.submit_game_high_score(
  p_game_name text,
  p_nickname text,
  p_score integer,
  p_last_stage integer default null
)
returns public.game_high_scores
language plpgsql
security definer
set search_path = public
as $$
declare
  normalized_game_name text := btrim(p_game_name);
  normalized_nickname text := btrim(p_nickname);
  result_row public.game_high_scores;
begin
  if normalized_game_name = '' then
    raise exception 'game_name is required' using errcode = '22023';
  end if;

  if normalized_nickname = '' then
    raise exception 'nickname is required' using errcode = '22023';
  end if;

  if p_score is null or p_score < 0 then
    raise exception 'score must be non-negative' using errcode = '22023';
  end if;

  if p_last_stage is not null and p_last_stage < 0 then
    raise exception 'last_stage must be non-negative' using errcode = '22023';
  end if;

  insert into public.game_high_scores as scores (
    game_name,
    nickname,
    score,
    last_stage
  )
  values (
    normalized_game_name,
    normalized_nickname,
    p_score,
    p_last_stage
  )
  on conflict (game_name, nickname) do update
    set score = excluded.score,
        last_stage = excluded.last_stage,
        updated_at = timezone('utc', now())
  where excluded.score > scores.score
     or coalesce(excluded.last_stage, -1) > coalesce(scores.last_stage, -1)
  returning * into result_row;

  if result_row.id is null then
    select *
    into result_row
    from public.game_high_scores
    where game_name = normalized_game_name
      and nickname = normalized_nickname;
  end if;

  return result_row;
end;
$$;

revoke all on public.game_high_scores from anon, authenticated;
grant select on public.game_high_scores to anon, authenticated;
revoke all on function public.submit_game_high_score(text, text, integer, integer) from public;
grant execute on function public.submit_game_high_score(text, text, integer, integer) to anon, authenticated;
